#!/bin/bash

# System Information
# to check the hostname 
hostname=$(hostname)
source /etc/os-release
#to access the os name
OS=$PRETTY_NAME

#to get the system uptime information
uptime=$(uptime -p)

# Hardware Information
#to obtain the product details such as cpu model, serial number,speed
cpu=$(lshw -class processor | awk '/product/ {print $2, $3, $4, $5}')
speed=$(lscpu | awk '/^CPU MHz/ {print $3}'&& lscpu | awk '/^CPU max MHz/ {print $4}')
#to check total memory size
ram=$(free -h | awk '/Mem/ {print $2}')
#to check the disk information including disk name, size and model
disks=$(lsblk -io NAME,SIZE,MODEL | grep -v "NAME")
#to extract the info of display devices(video cards)
video=$(lshw -class display | awk '/product/ {print $2, $3, $4, $5}')

# Network Information
#to check the domain name
fqdn=$(hostname -f)
#extract the ip address of fourth field
host_address=$(ip -o addr show | awk '/inet / {print $4}')
#represents the ip gateway
gateway=$(ip r | awk '/default/ {print $3}')
#represents the dns server
dns_server=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
#to check the name of the network interface
interface=$(ip -o addr show | awk '/scope global/ {print $2}')
#to obtain ip add
ip_address=$(ip -o -4 addr show | awk '{print $4}')

# System Status
#provide the name of currently logged-in user
users=$(who | awk '{print $1}' | sort | uniq)
#provide the disl space info
disk_space=$(df -h --output=source,avail | awk 'NR>1 {print $1, $2}')
#to check the count of running processes
process_count=$(ps -e --no-header | wc -l)
#to check the load average
load_averages=$(uptime | awk -F'average: ' '{print $2}' | awk -F', ' '{print $1, $2, $3}')
#to obtain the memory allocation information
memory_allocation=$(free -h | awk '/Mem:/ {print $3 "/" $2}')
#to ectract the info of listening ports
listening_ports=$(ss -tln | awk '/LISTEN/ {print $4}')
#the command is to obtain an overview of ufw rule configured
ufw_rules=$(grep "^\[" /etc/ufw/*.rules)

# Generate the report
echo
echo "System Report generated by $(whoami), $(date +%c)"
echo
echo "System Information"
echo "-------------------"
echo "Hostname: $hostname"
echo "OS: $OS"
echo "Uptime: $uptime"
echo
echo "Hardware Information"
echo "----------------------"
echo "CPU: $cpu"
echo "Speed: $speed"
echo "RAM: $ram"
echo "Disk(s):"
echo "$disks"
echo "Video: $video"
echo "Network Information"
echo "---------------------"
echo "FQDN: $fqdn"
echo "Host Address: $host_address"
echo "Gateway IP: $gateway"
echo "DNS server: $dns_server"
echo
echo "Interface: $interface"
echo "IP Address: $ip_address"
echo "System Status"
echo "--------------"
echo "Users Logged In: $users"
echo "Disk Space:"
echo "$disk_space"
echo "Process Count: $process_count"
echo "Load Averages: $load_averages"
echo "Memory Allocation: $memory_allocation"
echo "Listening Network Ports: $listening_ports"
echo "UFW Rules: $ufw_rules"
